name: MumzWorld Test Suite
 
on:
  push:
    branches:
      - master
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
 
      - name: Install dependencies
        run: mvn clean install -DskipTests
 
      - name: Run test suite
        run: mvn -X -e test
 
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/surefire-reports
