name: MumzWorld Test Suite

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      # Add this step to setup Node.js 16
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Verify Node.js version
        run: node -v  # This will print the Node.js version being used

      - name: Install dependencies
        run: mvn clean install

      - name: Run test suite
        run: mvn test

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports/extent-report.html

      - name: List files in reports directory
        run: ls -la reports
